name: cuda-cross-build

on: [push]

jobs:
  windows_cuda:
    name: cuda/release/windows
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.29
    - name: Install Cuda Toolkit 12.2 on Windows
      run: |
        mkdir -p "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2"
        choco install unzip -y
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/windows-x86_64/cuda_cudart-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/windows-x86_64/cuda_nvcc-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvrtc/windows-x86_64/cuda_nvrtc-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/windows-x86_64/libcublas-windows-x86_64-12.2.5.6-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvtx/windows-x86_64/cuda_nvtx-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/windows-x86_64/cuda_profiler_api-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/visual_studio_integration/windows-x86_64/visual_studio_integration-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprof/windows-x86_64/cuda_nvprof-windows-x86_64-12.2.128-archive.zip"
        curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/windows-x86_64/cuda_cccl-windows-x86_64-12.2.128-archive.zip"
        unzip '*.zip' -d "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2"
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_cudart-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_nvcc-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_nvrtc-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\libcublas-windows-x86_64-12.2.5.6-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_nvtx-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_profiler_api-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\visual_studio_integration-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_nvprof-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
        xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\cuda_cccl-windows-x86_64-12.2.128-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" /E /I /H /Y
    # Default installation path for CUDA Toolkit is C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2
    - name: Add Path
      run: |
        echo "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.2\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\libnvvp" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        echo "CUDA_PATH_V12_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
    - name: build
      run: |
      
        nvcc -g -maxrregcount 32 --resource-usage -lineinfo -Xptxas -lineinfo -v -O3 \
        --generate-code arch=compute_50,code=sm_50 --generate-code arch=compute_52,code=sm_52 \
        --generate-code arch=compute_60,code=sm_60 --generate-code arch=compute_61,code=sm_61 \
        --generate-code arch=compute_70,code=sm_70 --generate-code arch=compute_75,code=sm_75 \
        --generate-code arch=compute_80,code=sm_80 --generate-code arch=compute_86,code=sm_86 \
        --generate-code arch=compute_89,code=sm_89 \
        -m=64 -dlcm=cg main.cu -o loneliest-cuda.exe -diag-suppress 177 \
        -ID:\a\LoneliestSeed\LoneliestSeed\boinc\ -ID:\a\LoneliestSeed\LoneliestSeed\boinc\win\ \
        -LD:\a\LoneliestSeed\LoneliestSeed\boinc\lib\win\ \
        -lboinc_api -lboinc -lcuda -luser32 -DBOINC -D_WIN32 \
        -allow-unsupported-compiler
        dir
    - uses: actions/upload-artifact@v3
      with:
       name: loneliest-cuda-win
       path: .\loneliest*.exe
  linux_cuda:
    name: cuda/release/linux
    runs-on: [ubuntu-latest]
    container: nvidia/cuda:12.2.2-devel-ubuntu20.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        nvcc -g -maxrregcount 32 --resource-usage -lineinfo -Xptxas -lineinfo -v -O3 \
        --generate-code arch=compute_50,code=sm_50 --generate-code arch=compute_52,code=sm_52 \
        --generate-code arch=compute_60,code=sm_60 --generate-code arch=compute_61,code=sm_61 \
        --generate-code arch=compute_70,code=sm_70 --generate-code arch=compute_75,code=sm_75 \
        --generate-code arch=compute_80,code=sm_80 --generate-code arch=compute_86,code=sm_86 \
        --generate-code arch=compute_89,code=sm_89 \
        main.cu -m64 -o loneliest-cuda \
        -DBOINC -Iboinc/ -Lboinc/lib/lin -lcuda -lboinc_api -lboinc -Xptxas -v
        ls -la
    - uses: actions/upload-artifact@v3
      with:
       name: loneliest-cuda-lin
       path: ./loneliest-cuda*