name: cuda-cross-build

on: [push]

jobs:
  windows_cuda:
    name: cuda/release/windows
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: Jimver/cuda-toolkit@v0.2.19
    - name: build
      run: |
        nvcc --std c++20 -m=64 -O3 -Xptxas -dlcm=cg main.cu -o loneliest-cuda.exe -diag-suppress 177 -ID:\a\LoneliestSeed\LoneliestSeed\boinc\ -ID:\a\LoneliestSeed\LoneliestSeed\boinc\win\ -LD:\a\LoneliestSeed\LoneliestSeed\boinc\lib\win\ -lboinc_api -lboinc -lcuda -luser32 -DBOINC -D_WIN32
        dir
    - uses: actions/upload-artifact@v3
      with:
       name: loneliest-cuda-win
       path: .\loneliest*.exe
  linux_cuda:
    name: cuda/release/linux
    runs-on: [ubuntu-latest]
    container: nvidia/cuda:12.6.3-devel-ubuntu20.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        nvcc main.cu -Xcompiler -static-libgcc -Xcompiler -static-libstdc++ -m64 -O3 -o loneliest-cuda -DBOINC -Iboinc/ -Lboinc/lib/lin -lcuda -lboinc_api -lboinc -Xptxas -v
        ls -la
    - uses: actions/upload-artifact@v3
      with:
       name: loneliest-cuda-lin
       path: ./loneliest-cuda*